### ISSUE TITLE
show_birthday crashes when called for a user for whom no birthday is set

### ISSUE THREAD

**Issue by yevhenmazur** [cs100675jvv/project-f16df35s#27]
### Steps to reproduce:

1. Create a user without a birthday, for example username
2. Call show_birthday username

### Current behavior:
`
Traceback (most recent call last):
  File "/home/yudjin/Projects/project-f16df35s/main.py", line 189, in <module>
    main()
  File "/home/yudjin/Projects/project-f16df35s/main.py", line 139, in main
    result = show_birthday(args, book)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yudjin/Projects/project-f16df35s/_function/show.py", line 55, in show_birthday
    date_obj = datetime.strptime(str(record.birthday), "%Y-%m-%d %H:%M:%S")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'None' does not match format '%Y-%m-%d %H:%M:%S'
`

**Comment by yevhenmazur** [comment]
@cs100675jvv - FYI

**Comment by cs100675jvv** [comment]
Corrected
